server:
  port: 8882
spring:
  application:
    name: product-service
eureka:
  client:
    region: beijing
    availability-zones:
      beijing: zone1,zone2
    service-url:
      zone1: http://peer1:8880/eureka/
      zone2: http://peer2:8881/eureka/
